// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CompletionUsageCompletionTokensDetails) setDefaults() {
	{
		val := int(0)
		s.ReasoningTokens.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CompletionUsagePromptTokensDetails) setDefaults() {
	{
		val := int(0)
		s.CachedTokens.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateChatCompletionRequest) setDefaults() {
	{
		val := float64(1)
		s.Temperature.SetTo(val)
	}
	{
		val := float64(1)
		s.TopP.SetTo(val)
	}
	{
		val := int(1)
		s.N.SetTo(val)
	}
	{
		val := bool(false)
		s.Stream.SetTo(val)
	}
	{
		val := float64(0)
		s.PresencePenalty.SetTo(val)
	}
	{
		val := float64(0)
		s.FrequencyPenalty.SetTo(val)
	}
	{
		val := bool(false)
		s.Logprobs.SetTo(val)
	}
	{
		val := bool(true)
		s.ParallelToolCalls.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FunctionObject) setDefaults() {
	{
		val := bool(false)
		s.Strict.SetTo(val)
	}
}
