// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/ChatCompletionChoice
type ChatCompletionChoice struct {
	Index        int                                 `json:"index"`
	Message      ChatCompletionResponseMessage       `json:"message"`
	FinishReason NilChatCompletionChoiceFinishReason `json:"finish_reason"`
	Logprobs     OptNilChatCompletionChoiceLogprobs  `json:"logprobs"`
}

// GetIndex returns the value of Index.
func (s *ChatCompletionChoice) GetIndex() int {
	return s.Index
}

// GetMessage returns the value of Message.
func (s *ChatCompletionChoice) GetMessage() ChatCompletionResponseMessage {
	return s.Message
}

// GetFinishReason returns the value of FinishReason.
func (s *ChatCompletionChoice) GetFinishReason() NilChatCompletionChoiceFinishReason {
	return s.FinishReason
}

// GetLogprobs returns the value of Logprobs.
func (s *ChatCompletionChoice) GetLogprobs() OptNilChatCompletionChoiceLogprobs {
	return s.Logprobs
}

// SetIndex sets the value of Index.
func (s *ChatCompletionChoice) SetIndex(val int) {
	s.Index = val
}

// SetMessage sets the value of Message.
func (s *ChatCompletionChoice) SetMessage(val ChatCompletionResponseMessage) {
	s.Message = val
}

// SetFinishReason sets the value of FinishReason.
func (s *ChatCompletionChoice) SetFinishReason(val NilChatCompletionChoiceFinishReason) {
	s.FinishReason = val
}

// SetLogprobs sets the value of Logprobs.
func (s *ChatCompletionChoice) SetLogprobs(val OptNilChatCompletionChoiceLogprobs) {
	s.Logprobs = val
}

type ChatCompletionChoiceFinishReason string

const (
	ChatCompletionChoiceFinishReasonStop          ChatCompletionChoiceFinishReason = "stop"
	ChatCompletionChoiceFinishReasonLength        ChatCompletionChoiceFinishReason = "length"
	ChatCompletionChoiceFinishReasonToolCalls     ChatCompletionChoiceFinishReason = "tool_calls"
	ChatCompletionChoiceFinishReasonContentFilter ChatCompletionChoiceFinishReason = "content_filter"
)

// AllValues returns all ChatCompletionChoiceFinishReason values.
func (ChatCompletionChoiceFinishReason) AllValues() []ChatCompletionChoiceFinishReason {
	return []ChatCompletionChoiceFinishReason{
		ChatCompletionChoiceFinishReasonStop,
		ChatCompletionChoiceFinishReasonLength,
		ChatCompletionChoiceFinishReasonToolCalls,
		ChatCompletionChoiceFinishReasonContentFilter,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionChoiceFinishReason) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionChoiceFinishReasonStop:
		return []byte(s), nil
	case ChatCompletionChoiceFinishReasonLength:
		return []byte(s), nil
	case ChatCompletionChoiceFinishReasonToolCalls:
		return []byte(s), nil
	case ChatCompletionChoiceFinishReasonContentFilter:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionChoiceFinishReason) UnmarshalText(data []byte) error {
	switch ChatCompletionChoiceFinishReason(data) {
	case ChatCompletionChoiceFinishReasonStop:
		*s = ChatCompletionChoiceFinishReasonStop
		return nil
	case ChatCompletionChoiceFinishReasonLength:
		*s = ChatCompletionChoiceFinishReasonLength
		return nil
	case ChatCompletionChoiceFinishReasonToolCalls:
		*s = ChatCompletionChoiceFinishReasonToolCalls
		return nil
	case ChatCompletionChoiceFinishReasonContentFilter:
		*s = ChatCompletionChoiceFinishReasonContentFilter
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ChatCompletionChoiceLogprobs struct {
	Content OptNilChatCompletionTokenLogprobArray `json:"content"`
}

// GetContent returns the value of Content.
func (s *ChatCompletionChoiceLogprobs) GetContent() OptNilChatCompletionTokenLogprobArray {
	return s.Content
}

// SetContent sets the value of Content.
func (s *ChatCompletionChoiceLogprobs) SetContent(val OptNilChatCompletionTokenLogprobArray) {
	s.Content = val
}

// Ref: #/components/schemas/ChatCompletionContentPart
type ChatCompletionContentPart struct {
	Type     ChatCompletionContentPartType        `json:"type"`
	Text     OptString                            `json:"text"`
	ImageURL OptChatCompletionContentPartImageURL `json:"image_url"`
}

// GetType returns the value of Type.
func (s *ChatCompletionContentPart) GetType() ChatCompletionContentPartType {
	return s.Type
}

// GetText returns the value of Text.
func (s *ChatCompletionContentPart) GetText() OptString {
	return s.Text
}

// GetImageURL returns the value of ImageURL.
func (s *ChatCompletionContentPart) GetImageURL() OptChatCompletionContentPartImageURL {
	return s.ImageURL
}

// SetType sets the value of Type.
func (s *ChatCompletionContentPart) SetType(val ChatCompletionContentPartType) {
	s.Type = val
}

// SetText sets the value of Text.
func (s *ChatCompletionContentPart) SetText(val OptString) {
	s.Text = val
}

// SetImageURL sets the value of ImageURL.
func (s *ChatCompletionContentPart) SetImageURL(val OptChatCompletionContentPartImageURL) {
	s.ImageURL = val
}

type ChatCompletionContentPartImageURL struct {
	URL    OptString                                  `json:"url"`
	Detail OptChatCompletionContentPartImageURLDetail `json:"detail"`
}

// GetURL returns the value of URL.
func (s *ChatCompletionContentPartImageURL) GetURL() OptString {
	return s.URL
}

// GetDetail returns the value of Detail.
func (s *ChatCompletionContentPartImageURL) GetDetail() OptChatCompletionContentPartImageURLDetail {
	return s.Detail
}

// SetURL sets the value of URL.
func (s *ChatCompletionContentPartImageURL) SetURL(val OptString) {
	s.URL = val
}

// SetDetail sets the value of Detail.
func (s *ChatCompletionContentPartImageURL) SetDetail(val OptChatCompletionContentPartImageURLDetail) {
	s.Detail = val
}

type ChatCompletionContentPartImageURLDetail string

const (
	ChatCompletionContentPartImageURLDetailAuto ChatCompletionContentPartImageURLDetail = "auto"
	ChatCompletionContentPartImageURLDetailLow  ChatCompletionContentPartImageURLDetail = "low"
	ChatCompletionContentPartImageURLDetailHigh ChatCompletionContentPartImageURLDetail = "high"
)

// AllValues returns all ChatCompletionContentPartImageURLDetail values.
func (ChatCompletionContentPartImageURLDetail) AllValues() []ChatCompletionContentPartImageURLDetail {
	return []ChatCompletionContentPartImageURLDetail{
		ChatCompletionContentPartImageURLDetailAuto,
		ChatCompletionContentPartImageURLDetailLow,
		ChatCompletionContentPartImageURLDetailHigh,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionContentPartImageURLDetail) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionContentPartImageURLDetailAuto:
		return []byte(s), nil
	case ChatCompletionContentPartImageURLDetailLow:
		return []byte(s), nil
	case ChatCompletionContentPartImageURLDetailHigh:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionContentPartImageURLDetail) UnmarshalText(data []byte) error {
	switch ChatCompletionContentPartImageURLDetail(data) {
	case ChatCompletionContentPartImageURLDetailAuto:
		*s = ChatCompletionContentPartImageURLDetailAuto
		return nil
	case ChatCompletionContentPartImageURLDetailLow:
		*s = ChatCompletionContentPartImageURLDetailLow
		return nil
	case ChatCompletionContentPartImageURLDetailHigh:
		*s = ChatCompletionContentPartImageURLDetailHigh
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ChatCompletionContentPartType string

const (
	ChatCompletionContentPartTypeText     ChatCompletionContentPartType = "text"
	ChatCompletionContentPartTypeImageURL ChatCompletionContentPartType = "image_url"
)

// AllValues returns all ChatCompletionContentPartType values.
func (ChatCompletionContentPartType) AllValues() []ChatCompletionContentPartType {
	return []ChatCompletionContentPartType{
		ChatCompletionContentPartTypeText,
		ChatCompletionContentPartTypeImageURL,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionContentPartType) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionContentPartTypeText:
		return []byte(s), nil
	case ChatCompletionContentPartTypeImageURL:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionContentPartType) UnmarshalText(data []byte) error {
	switch ChatCompletionContentPartType(data) {
	case ChatCompletionContentPartTypeText:
		*s = ChatCompletionContentPartTypeText
		return nil
	case ChatCompletionContentPartTypeImageURL:
		*s = ChatCompletionContentPartTypeImageURL
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionMessageToolCall
type ChatCompletionMessageToolCall struct {
	ID       string                                `json:"id"`
	Type     ChatCompletionMessageToolCallType     `json:"type"`
	Function ChatCompletionMessageToolCallFunction `json:"function"`
}

// GetID returns the value of ID.
func (s *ChatCompletionMessageToolCall) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *ChatCompletionMessageToolCall) GetType() ChatCompletionMessageToolCallType {
	return s.Type
}

// GetFunction returns the value of Function.
func (s *ChatCompletionMessageToolCall) GetFunction() ChatCompletionMessageToolCallFunction {
	return s.Function
}

// SetID sets the value of ID.
func (s *ChatCompletionMessageToolCall) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *ChatCompletionMessageToolCall) SetType(val ChatCompletionMessageToolCallType) {
	s.Type = val
}

// SetFunction sets the value of Function.
func (s *ChatCompletionMessageToolCall) SetFunction(val ChatCompletionMessageToolCallFunction) {
	s.Function = val
}

type ChatCompletionMessageToolCallFunction struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// GetName returns the value of Name.
func (s *ChatCompletionMessageToolCallFunction) GetName() string {
	return s.Name
}

// GetArguments returns the value of Arguments.
func (s *ChatCompletionMessageToolCallFunction) GetArguments() string {
	return s.Arguments
}

// SetName sets the value of Name.
func (s *ChatCompletionMessageToolCallFunction) SetName(val string) {
	s.Name = val
}

// SetArguments sets the value of Arguments.
func (s *ChatCompletionMessageToolCallFunction) SetArguments(val string) {
	s.Arguments = val
}

type ChatCompletionMessageToolCallType string

const (
	ChatCompletionMessageToolCallTypeFunction ChatCompletionMessageToolCallType = "function"
)

// AllValues returns all ChatCompletionMessageToolCallType values.
func (ChatCompletionMessageToolCallType) AllValues() []ChatCompletionMessageToolCallType {
	return []ChatCompletionMessageToolCallType{
		ChatCompletionMessageToolCallTypeFunction,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionMessageToolCallType) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionMessageToolCallTypeFunction:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionMessageToolCallType) UnmarshalText(data []byte) error {
	switch ChatCompletionMessageToolCallType(data) {
	case ChatCompletionMessageToolCallTypeFunction:
		*s = ChatCompletionMessageToolCallTypeFunction
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionNamedToolChoice
type ChatCompletionNamedToolChoice struct {
	Type     ChatCompletionNamedToolChoiceType     `json:"type"`
	Function ChatCompletionNamedToolChoiceFunction `json:"function"`
}

// GetType returns the value of Type.
func (s *ChatCompletionNamedToolChoice) GetType() ChatCompletionNamedToolChoiceType {
	return s.Type
}

// GetFunction returns the value of Function.
func (s *ChatCompletionNamedToolChoice) GetFunction() ChatCompletionNamedToolChoiceFunction {
	return s.Function
}

// SetType sets the value of Type.
func (s *ChatCompletionNamedToolChoice) SetType(val ChatCompletionNamedToolChoiceType) {
	s.Type = val
}

// SetFunction sets the value of Function.
func (s *ChatCompletionNamedToolChoice) SetFunction(val ChatCompletionNamedToolChoiceFunction) {
	s.Function = val
}

type ChatCompletionNamedToolChoiceFunction struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *ChatCompletionNamedToolChoiceFunction) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *ChatCompletionNamedToolChoiceFunction) SetName(val string) {
	s.Name = val
}

type ChatCompletionNamedToolChoiceType string

const (
	ChatCompletionNamedToolChoiceTypeFunction ChatCompletionNamedToolChoiceType = "function"
)

// AllValues returns all ChatCompletionNamedToolChoiceType values.
func (ChatCompletionNamedToolChoiceType) AllValues() []ChatCompletionNamedToolChoiceType {
	return []ChatCompletionNamedToolChoiceType{
		ChatCompletionNamedToolChoiceTypeFunction,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionNamedToolChoiceType) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionNamedToolChoiceTypeFunction:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionNamedToolChoiceType) UnmarshalText(data []byte) error {
	switch ChatCompletionNamedToolChoiceType(data) {
	case ChatCompletionNamedToolChoiceTypeFunction:
		*s = ChatCompletionNamedToolChoiceTypeFunction
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionRequestMessage
type ChatCompletionRequestMessage struct {
	Role       ChatCompletionRequestMessageRole          `json:"role"`
	Content    OptNilChatCompletionRequestMessageContent `json:"content"`
	Name       OptString                                 `json:"name"`
	ToolCalls  []ChatCompletionMessageToolCall           `json:"tool_calls"`
	ToolCallID OptString                                 `json:"tool_call_id"`
}

// GetRole returns the value of Role.
func (s *ChatCompletionRequestMessage) GetRole() ChatCompletionRequestMessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *ChatCompletionRequestMessage) GetContent() OptNilChatCompletionRequestMessageContent {
	return s.Content
}

// GetName returns the value of Name.
func (s *ChatCompletionRequestMessage) GetName() OptString {
	return s.Name
}

// GetToolCalls returns the value of ToolCalls.
func (s *ChatCompletionRequestMessage) GetToolCalls() []ChatCompletionMessageToolCall {
	return s.ToolCalls
}

// GetToolCallID returns the value of ToolCallID.
func (s *ChatCompletionRequestMessage) GetToolCallID() OptString {
	return s.ToolCallID
}

// SetRole sets the value of Role.
func (s *ChatCompletionRequestMessage) SetRole(val ChatCompletionRequestMessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *ChatCompletionRequestMessage) SetContent(val OptNilChatCompletionRequestMessageContent) {
	s.Content = val
}

// SetName sets the value of Name.
func (s *ChatCompletionRequestMessage) SetName(val OptString) {
	s.Name = val
}

// SetToolCalls sets the value of ToolCalls.
func (s *ChatCompletionRequestMessage) SetToolCalls(val []ChatCompletionMessageToolCall) {
	s.ToolCalls = val
}

// SetToolCallID sets the value of ToolCallID.
func (s *ChatCompletionRequestMessage) SetToolCallID(val OptString) {
	s.ToolCallID = val
}

// ChatCompletionRequestMessageContent represents sum type.
type ChatCompletionRequestMessageContent struct {
	Type                           ChatCompletionRequestMessageContentType // switch on this field
	String                         string
	ChatCompletionContentPartArray []ChatCompletionContentPart
}

// ChatCompletionRequestMessageContentType is oneOf type of ChatCompletionRequestMessageContent.
type ChatCompletionRequestMessageContentType string

// Possible values for ChatCompletionRequestMessageContentType.
const (
	StringChatCompletionRequestMessageContent                         ChatCompletionRequestMessageContentType = "string"
	ChatCompletionContentPartArrayChatCompletionRequestMessageContent ChatCompletionRequestMessageContentType = "[]ChatCompletionContentPart"
)

// IsString reports whether ChatCompletionRequestMessageContent is string.
func (s ChatCompletionRequestMessageContent) IsString() bool {
	return s.Type == StringChatCompletionRequestMessageContent
}

// IsChatCompletionContentPartArray reports whether ChatCompletionRequestMessageContent is []ChatCompletionContentPart.
func (s ChatCompletionRequestMessageContent) IsChatCompletionContentPartArray() bool {
	return s.Type == ChatCompletionContentPartArrayChatCompletionRequestMessageContent
}

// SetString sets ChatCompletionRequestMessageContent to string.
func (s *ChatCompletionRequestMessageContent) SetString(v string) {
	s.Type = StringChatCompletionRequestMessageContent
	s.String = v
}

// GetString returns string and true boolean if ChatCompletionRequestMessageContent is string.
func (s ChatCompletionRequestMessageContent) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringChatCompletionRequestMessageContent returns new ChatCompletionRequestMessageContent from string.
func NewStringChatCompletionRequestMessageContent(v string) ChatCompletionRequestMessageContent {
	var s ChatCompletionRequestMessageContent
	s.SetString(v)
	return s
}

// SetChatCompletionContentPartArray sets ChatCompletionRequestMessageContent to []ChatCompletionContentPart.
func (s *ChatCompletionRequestMessageContent) SetChatCompletionContentPartArray(v []ChatCompletionContentPart) {
	s.Type = ChatCompletionContentPartArrayChatCompletionRequestMessageContent
	s.ChatCompletionContentPartArray = v
}

// GetChatCompletionContentPartArray returns []ChatCompletionContentPart and true boolean if ChatCompletionRequestMessageContent is []ChatCompletionContentPart.
func (s ChatCompletionRequestMessageContent) GetChatCompletionContentPartArray() (v []ChatCompletionContentPart, ok bool) {
	if !s.IsChatCompletionContentPartArray() {
		return v, false
	}
	return s.ChatCompletionContentPartArray, true
}

// NewChatCompletionContentPartArrayChatCompletionRequestMessageContent returns new ChatCompletionRequestMessageContent from []ChatCompletionContentPart.
func NewChatCompletionContentPartArrayChatCompletionRequestMessageContent(v []ChatCompletionContentPart) ChatCompletionRequestMessageContent {
	var s ChatCompletionRequestMessageContent
	s.SetChatCompletionContentPartArray(v)
	return s
}

type ChatCompletionRequestMessageRole string

const (
	ChatCompletionRequestMessageRoleSystem    ChatCompletionRequestMessageRole = "system"
	ChatCompletionRequestMessageRoleUser      ChatCompletionRequestMessageRole = "user"
	ChatCompletionRequestMessageRoleAssistant ChatCompletionRequestMessageRole = "assistant"
	ChatCompletionRequestMessageRoleTool      ChatCompletionRequestMessageRole = "tool"
)

// AllValues returns all ChatCompletionRequestMessageRole values.
func (ChatCompletionRequestMessageRole) AllValues() []ChatCompletionRequestMessageRole {
	return []ChatCompletionRequestMessageRole{
		ChatCompletionRequestMessageRoleSystem,
		ChatCompletionRequestMessageRoleUser,
		ChatCompletionRequestMessageRoleAssistant,
		ChatCompletionRequestMessageRoleTool,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionRequestMessageRole) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionRequestMessageRoleSystem:
		return []byte(s), nil
	case ChatCompletionRequestMessageRoleUser:
		return []byte(s), nil
	case ChatCompletionRequestMessageRoleAssistant:
		return []byte(s), nil
	case ChatCompletionRequestMessageRoleTool:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionRequestMessageRole) UnmarshalText(data []byte) error {
	switch ChatCompletionRequestMessageRole(data) {
	case ChatCompletionRequestMessageRoleSystem:
		*s = ChatCompletionRequestMessageRoleSystem
		return nil
	case ChatCompletionRequestMessageRoleUser:
		*s = ChatCompletionRequestMessageRoleUser
		return nil
	case ChatCompletionRequestMessageRoleAssistant:
		*s = ChatCompletionRequestMessageRoleAssistant
		return nil
	case ChatCompletionRequestMessageRoleTool:
		*s = ChatCompletionRequestMessageRoleTool
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionResponseMessage
type ChatCompletionResponseMessage struct {
	Role      ChatCompletionResponseMessageRole `json:"role"`
	Content   NilString                         `json:"content"`
	ToolCalls []ChatCompletionMessageToolCall   `json:"tool_calls"`
	Refusal   OptNilString                      `json:"refusal"`
}

// GetRole returns the value of Role.
func (s *ChatCompletionResponseMessage) GetRole() ChatCompletionResponseMessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *ChatCompletionResponseMessage) GetContent() NilString {
	return s.Content
}

// GetToolCalls returns the value of ToolCalls.
func (s *ChatCompletionResponseMessage) GetToolCalls() []ChatCompletionMessageToolCall {
	return s.ToolCalls
}

// GetRefusal returns the value of Refusal.
func (s *ChatCompletionResponseMessage) GetRefusal() OptNilString {
	return s.Refusal
}

// SetRole sets the value of Role.
func (s *ChatCompletionResponseMessage) SetRole(val ChatCompletionResponseMessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *ChatCompletionResponseMessage) SetContent(val NilString) {
	s.Content = val
}

// SetToolCalls sets the value of ToolCalls.
func (s *ChatCompletionResponseMessage) SetToolCalls(val []ChatCompletionMessageToolCall) {
	s.ToolCalls = val
}

// SetRefusal sets the value of Refusal.
func (s *ChatCompletionResponseMessage) SetRefusal(val OptNilString) {
	s.Refusal = val
}

type ChatCompletionResponseMessageRole string

const (
	ChatCompletionResponseMessageRoleAssistant ChatCompletionResponseMessageRole = "assistant"
)

// AllValues returns all ChatCompletionResponseMessageRole values.
func (ChatCompletionResponseMessageRole) AllValues() []ChatCompletionResponseMessageRole {
	return []ChatCompletionResponseMessageRole{
		ChatCompletionResponseMessageRoleAssistant,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionResponseMessageRole) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionResponseMessageRoleAssistant:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionResponseMessageRole) UnmarshalText(data []byte) error {
	switch ChatCompletionResponseMessageRole(data) {
	case ChatCompletionResponseMessageRoleAssistant:
		*s = ChatCompletionResponseMessageRoleAssistant
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionTokenLogprob
type ChatCompletionTokenLogprob struct {
	Token       string                                      `json:"token"`
	Logprob     float64                                     `json:"logprob"`
	Bytes       []int                                       `json:"bytes"`
	TopLogprobs []ChatCompletionTokenLogprobTopLogprobsItem `json:"top_logprobs"`
}

// GetToken returns the value of Token.
func (s *ChatCompletionTokenLogprob) GetToken() string {
	return s.Token
}

// GetLogprob returns the value of Logprob.
func (s *ChatCompletionTokenLogprob) GetLogprob() float64 {
	return s.Logprob
}

// GetBytes returns the value of Bytes.
func (s *ChatCompletionTokenLogprob) GetBytes() []int {
	return s.Bytes
}

// GetTopLogprobs returns the value of TopLogprobs.
func (s *ChatCompletionTokenLogprob) GetTopLogprobs() []ChatCompletionTokenLogprobTopLogprobsItem {
	return s.TopLogprobs
}

// SetToken sets the value of Token.
func (s *ChatCompletionTokenLogprob) SetToken(val string) {
	s.Token = val
}

// SetLogprob sets the value of Logprob.
func (s *ChatCompletionTokenLogprob) SetLogprob(val float64) {
	s.Logprob = val
}

// SetBytes sets the value of Bytes.
func (s *ChatCompletionTokenLogprob) SetBytes(val []int) {
	s.Bytes = val
}

// SetTopLogprobs sets the value of TopLogprobs.
func (s *ChatCompletionTokenLogprob) SetTopLogprobs(val []ChatCompletionTokenLogprobTopLogprobsItem) {
	s.TopLogprobs = val
}

type ChatCompletionTokenLogprobTopLogprobsItem struct {
	Token   string  `json:"token"`
	Logprob float64 `json:"logprob"`
	Bytes   []int   `json:"bytes"`
}

// GetToken returns the value of Token.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) GetToken() string {
	return s.Token
}

// GetLogprob returns the value of Logprob.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) GetLogprob() float64 {
	return s.Logprob
}

// GetBytes returns the value of Bytes.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) GetBytes() []int {
	return s.Bytes
}

// SetToken sets the value of Token.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) SetToken(val string) {
	s.Token = val
}

// SetLogprob sets the value of Logprob.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) SetLogprob(val float64) {
	s.Logprob = val
}

// SetBytes sets the value of Bytes.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) SetBytes(val []int) {
	s.Bytes = val
}

// Ref: #/components/schemas/ChatCompletionTool
type ChatCompletionTool struct {
	Type     ChatCompletionToolType `json:"type"`
	Function FunctionObject         `json:"function"`
}

// GetType returns the value of Type.
func (s *ChatCompletionTool) GetType() ChatCompletionToolType {
	return s.Type
}

// GetFunction returns the value of Function.
func (s *ChatCompletionTool) GetFunction() FunctionObject {
	return s.Function
}

// SetType sets the value of Type.
func (s *ChatCompletionTool) SetType(val ChatCompletionToolType) {
	s.Type = val
}

// SetFunction sets the value of Function.
func (s *ChatCompletionTool) SetFunction(val FunctionObject) {
	s.Function = val
}

type ChatCompletionToolType string

const (
	ChatCompletionToolTypeFunction ChatCompletionToolType = "function"
)

// AllValues returns all ChatCompletionToolType values.
func (ChatCompletionToolType) AllValues() []ChatCompletionToolType {
	return []ChatCompletionToolType{
		ChatCompletionToolTypeFunction,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionToolType) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionToolTypeFunction:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionToolType) UnmarshalText(data []byte) error {
	switch ChatCompletionToolType(data) {
	case ChatCompletionToolTypeFunction:
		*s = ChatCompletionToolTypeFunction
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CompletionUsage
type CompletionUsage struct {
	PromptTokens            int                                       `json:"prompt_tokens"`
	CompletionTokens        int                                       `json:"completion_tokens"`
	TotalTokens             int                                       `json:"total_tokens"`
	CompletionTokensDetails OptCompletionUsageCompletionTokensDetails `json:"completion_tokens_details"`
	PromptTokensDetails     OptCompletionUsagePromptTokensDetails     `json:"prompt_tokens_details"`
}

// GetPromptTokens returns the value of PromptTokens.
func (s *CompletionUsage) GetPromptTokens() int {
	return s.PromptTokens
}

// GetCompletionTokens returns the value of CompletionTokens.
func (s *CompletionUsage) GetCompletionTokens() int {
	return s.CompletionTokens
}

// GetTotalTokens returns the value of TotalTokens.
func (s *CompletionUsage) GetTotalTokens() int {
	return s.TotalTokens
}

// GetCompletionTokensDetails returns the value of CompletionTokensDetails.
func (s *CompletionUsage) GetCompletionTokensDetails() OptCompletionUsageCompletionTokensDetails {
	return s.CompletionTokensDetails
}

// GetPromptTokensDetails returns the value of PromptTokensDetails.
func (s *CompletionUsage) GetPromptTokensDetails() OptCompletionUsagePromptTokensDetails {
	return s.PromptTokensDetails
}

// SetPromptTokens sets the value of PromptTokens.
func (s *CompletionUsage) SetPromptTokens(val int) {
	s.PromptTokens = val
}

// SetCompletionTokens sets the value of CompletionTokens.
func (s *CompletionUsage) SetCompletionTokens(val int) {
	s.CompletionTokens = val
}

// SetTotalTokens sets the value of TotalTokens.
func (s *CompletionUsage) SetTotalTokens(val int) {
	s.TotalTokens = val
}

// SetCompletionTokensDetails sets the value of CompletionTokensDetails.
func (s *CompletionUsage) SetCompletionTokensDetails(val OptCompletionUsageCompletionTokensDetails) {
	s.CompletionTokensDetails = val
}

// SetPromptTokensDetails sets the value of PromptTokensDetails.
func (s *CompletionUsage) SetPromptTokensDetails(val OptCompletionUsagePromptTokensDetails) {
	s.PromptTokensDetails = val
}

type CompletionUsageCompletionTokensDetails struct {
	ReasoningTokens OptInt `json:"reasoning_tokens"`
}

// GetReasoningTokens returns the value of ReasoningTokens.
func (s *CompletionUsageCompletionTokensDetails) GetReasoningTokens() OptInt {
	return s.ReasoningTokens
}

// SetReasoningTokens sets the value of ReasoningTokens.
func (s *CompletionUsageCompletionTokensDetails) SetReasoningTokens(val OptInt) {
	s.ReasoningTokens = val
}

type CompletionUsagePromptTokensDetails struct {
	CachedTokens OptInt `json:"cached_tokens"`
}

// GetCachedTokens returns the value of CachedTokens.
func (s *CompletionUsagePromptTokensDetails) GetCachedTokens() OptInt {
	return s.CachedTokens
}

// SetCachedTokens sets the value of CachedTokens.
func (s *CompletionUsagePromptTokensDetails) SetCachedTokens(val OptInt) {
	s.CachedTokens = val
}

// Ref: #/components/schemas/CreateChatCompletionRequest
type CreateChatCompletionRequest struct {
	Model               string                                         `json:"model"`
	Messages            []ChatCompletionRequestMessage                 `json:"messages"`
	Temperature         OptNilFloat64                                  `json:"temperature"`
	TopP                OptNilFloat64                                  `json:"top_p"`
	N                   OptNilInt                                      `json:"n"`
	Stream              OptNilBool                                     `json:"stream"`
	Stop                OptNilCreateChatCompletionRequestStop          `json:"stop"`
	MaxTokens           OptNilInt                                      `json:"max_tokens"`
	MaxCompletionTokens OptNilInt                                      `json:"max_completion_tokens"`
	PresencePenalty     OptNilFloat64                                  `json:"presence_penalty"`
	FrequencyPenalty    OptNilFloat64                                  `json:"frequency_penalty"`
	LogitBias           OptNilCreateChatCompletionRequestLogitBias     `json:"logit_bias"`
	Logprobs            OptNilBool                                     `json:"logprobs"`
	TopLogprobs         OptNilInt                                      `json:"top_logprobs"`
	User                OptString                                      `json:"user"`
	Seed                OptNilInt                                      `json:"seed"`
	Tools               []ChatCompletionTool                           `json:"tools"`
	ToolChoice          OptCreateChatCompletionRequestToolChoice       `json:"tool_choice"`
	ParallelToolCalls   OptBool                                        `json:"parallel_tool_calls"`
	StreamOptions       OptNilCreateChatCompletionRequestStreamOptions `json:"stream_options"`
	ResponseFormat      OptCreateChatCompletionRequestResponseFormat   `json:"response_format"`
}

// GetModel returns the value of Model.
func (s *CreateChatCompletionRequest) GetModel() string {
	return s.Model
}

// GetMessages returns the value of Messages.
func (s *CreateChatCompletionRequest) GetMessages() []ChatCompletionRequestMessage {
	return s.Messages
}

// GetTemperature returns the value of Temperature.
func (s *CreateChatCompletionRequest) GetTemperature() OptNilFloat64 {
	return s.Temperature
}

// GetTopP returns the value of TopP.
func (s *CreateChatCompletionRequest) GetTopP() OptNilFloat64 {
	return s.TopP
}

// GetN returns the value of N.
func (s *CreateChatCompletionRequest) GetN() OptNilInt {
	return s.N
}

// GetStream returns the value of Stream.
func (s *CreateChatCompletionRequest) GetStream() OptNilBool {
	return s.Stream
}

// GetStop returns the value of Stop.
func (s *CreateChatCompletionRequest) GetStop() OptNilCreateChatCompletionRequestStop {
	return s.Stop
}

// GetMaxTokens returns the value of MaxTokens.
func (s *CreateChatCompletionRequest) GetMaxTokens() OptNilInt {
	return s.MaxTokens
}

// GetMaxCompletionTokens returns the value of MaxCompletionTokens.
func (s *CreateChatCompletionRequest) GetMaxCompletionTokens() OptNilInt {
	return s.MaxCompletionTokens
}

// GetPresencePenalty returns the value of PresencePenalty.
func (s *CreateChatCompletionRequest) GetPresencePenalty() OptNilFloat64 {
	return s.PresencePenalty
}

// GetFrequencyPenalty returns the value of FrequencyPenalty.
func (s *CreateChatCompletionRequest) GetFrequencyPenalty() OptNilFloat64 {
	return s.FrequencyPenalty
}

// GetLogitBias returns the value of LogitBias.
func (s *CreateChatCompletionRequest) GetLogitBias() OptNilCreateChatCompletionRequestLogitBias {
	return s.LogitBias
}

// GetLogprobs returns the value of Logprobs.
func (s *CreateChatCompletionRequest) GetLogprobs() OptNilBool {
	return s.Logprobs
}

// GetTopLogprobs returns the value of TopLogprobs.
func (s *CreateChatCompletionRequest) GetTopLogprobs() OptNilInt {
	return s.TopLogprobs
}

// GetUser returns the value of User.
func (s *CreateChatCompletionRequest) GetUser() OptString {
	return s.User
}

// GetSeed returns the value of Seed.
func (s *CreateChatCompletionRequest) GetSeed() OptNilInt {
	return s.Seed
}

// GetTools returns the value of Tools.
func (s *CreateChatCompletionRequest) GetTools() []ChatCompletionTool {
	return s.Tools
}

// GetToolChoice returns the value of ToolChoice.
func (s *CreateChatCompletionRequest) GetToolChoice() OptCreateChatCompletionRequestToolChoice {
	return s.ToolChoice
}

// GetParallelToolCalls returns the value of ParallelToolCalls.
func (s *CreateChatCompletionRequest) GetParallelToolCalls() OptBool {
	return s.ParallelToolCalls
}

// GetStreamOptions returns the value of StreamOptions.
func (s *CreateChatCompletionRequest) GetStreamOptions() OptNilCreateChatCompletionRequestStreamOptions {
	return s.StreamOptions
}

// GetResponseFormat returns the value of ResponseFormat.
func (s *CreateChatCompletionRequest) GetResponseFormat() OptCreateChatCompletionRequestResponseFormat {
	return s.ResponseFormat
}

// SetModel sets the value of Model.
func (s *CreateChatCompletionRequest) SetModel(val string) {
	s.Model = val
}

// SetMessages sets the value of Messages.
func (s *CreateChatCompletionRequest) SetMessages(val []ChatCompletionRequestMessage) {
	s.Messages = val
}

// SetTemperature sets the value of Temperature.
func (s *CreateChatCompletionRequest) SetTemperature(val OptNilFloat64) {
	s.Temperature = val
}

// SetTopP sets the value of TopP.
func (s *CreateChatCompletionRequest) SetTopP(val OptNilFloat64) {
	s.TopP = val
}

// SetN sets the value of N.
func (s *CreateChatCompletionRequest) SetN(val OptNilInt) {
	s.N = val
}

// SetStream sets the value of Stream.
func (s *CreateChatCompletionRequest) SetStream(val OptNilBool) {
	s.Stream = val
}

// SetStop sets the value of Stop.
func (s *CreateChatCompletionRequest) SetStop(val OptNilCreateChatCompletionRequestStop) {
	s.Stop = val
}

// SetMaxTokens sets the value of MaxTokens.
func (s *CreateChatCompletionRequest) SetMaxTokens(val OptNilInt) {
	s.MaxTokens = val
}

// SetMaxCompletionTokens sets the value of MaxCompletionTokens.
func (s *CreateChatCompletionRequest) SetMaxCompletionTokens(val OptNilInt) {
	s.MaxCompletionTokens = val
}

// SetPresencePenalty sets the value of PresencePenalty.
func (s *CreateChatCompletionRequest) SetPresencePenalty(val OptNilFloat64) {
	s.PresencePenalty = val
}

// SetFrequencyPenalty sets the value of FrequencyPenalty.
func (s *CreateChatCompletionRequest) SetFrequencyPenalty(val OptNilFloat64) {
	s.FrequencyPenalty = val
}

// SetLogitBias sets the value of LogitBias.
func (s *CreateChatCompletionRequest) SetLogitBias(val OptNilCreateChatCompletionRequestLogitBias) {
	s.LogitBias = val
}

// SetLogprobs sets the value of Logprobs.
func (s *CreateChatCompletionRequest) SetLogprobs(val OptNilBool) {
	s.Logprobs = val
}

// SetTopLogprobs sets the value of TopLogprobs.
func (s *CreateChatCompletionRequest) SetTopLogprobs(val OptNilInt) {
	s.TopLogprobs = val
}

// SetUser sets the value of User.
func (s *CreateChatCompletionRequest) SetUser(val OptString) {
	s.User = val
}

// SetSeed sets the value of Seed.
func (s *CreateChatCompletionRequest) SetSeed(val OptNilInt) {
	s.Seed = val
}

// SetTools sets the value of Tools.
func (s *CreateChatCompletionRequest) SetTools(val []ChatCompletionTool) {
	s.Tools = val
}

// SetToolChoice sets the value of ToolChoice.
func (s *CreateChatCompletionRequest) SetToolChoice(val OptCreateChatCompletionRequestToolChoice) {
	s.ToolChoice = val
}

// SetParallelToolCalls sets the value of ParallelToolCalls.
func (s *CreateChatCompletionRequest) SetParallelToolCalls(val OptBool) {
	s.ParallelToolCalls = val
}

// SetStreamOptions sets the value of StreamOptions.
func (s *CreateChatCompletionRequest) SetStreamOptions(val OptNilCreateChatCompletionRequestStreamOptions) {
	s.StreamOptions = val
}

// SetResponseFormat sets the value of ResponseFormat.
func (s *CreateChatCompletionRequest) SetResponseFormat(val OptCreateChatCompletionRequestResponseFormat) {
	s.ResponseFormat = val
}

type CreateChatCompletionRequestLogitBias map[string]int

func (s *CreateChatCompletionRequestLogitBias) init() CreateChatCompletionRequestLogitBias {
	m := *s
	if m == nil {
		m = map[string]int{}
		*s = m
	}
	return m
}

type CreateChatCompletionRequestResponseFormat struct {
	Type       OptCreateChatCompletionRequestResponseFormatType       `json:"type"`
	JSONSchema OptCreateChatCompletionRequestResponseFormatJSONSchema `json:"json_schema"`
}

// GetType returns the value of Type.
func (s *CreateChatCompletionRequestResponseFormat) GetType() OptCreateChatCompletionRequestResponseFormatType {
	return s.Type
}

// GetJSONSchema returns the value of JSONSchema.
func (s *CreateChatCompletionRequestResponseFormat) GetJSONSchema() OptCreateChatCompletionRequestResponseFormatJSONSchema {
	return s.JSONSchema
}

// SetType sets the value of Type.
func (s *CreateChatCompletionRequestResponseFormat) SetType(val OptCreateChatCompletionRequestResponseFormatType) {
	s.Type = val
}

// SetJSONSchema sets the value of JSONSchema.
func (s *CreateChatCompletionRequestResponseFormat) SetJSONSchema(val OptCreateChatCompletionRequestResponseFormatJSONSchema) {
	s.JSONSchema = val
}

type CreateChatCompletionRequestResponseFormatJSONSchema struct {
	Name        OptString                                                    `json:"name"`
	Description OptString                                                    `json:"description"`
	Schema      OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema `json:"schema"`
	Strict      OptNilBool                                                   `json:"strict"`
}

// GetName returns the value of Name.
func (s *CreateChatCompletionRequestResponseFormatJSONSchema) GetName() OptString {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateChatCompletionRequestResponseFormatJSONSchema) GetDescription() OptString {
	return s.Description
}

// GetSchema returns the value of Schema.
func (s *CreateChatCompletionRequestResponseFormatJSONSchema) GetSchema() OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema {
	return s.Schema
}

// GetStrict returns the value of Strict.
func (s *CreateChatCompletionRequestResponseFormatJSONSchema) GetStrict() OptNilBool {
	return s.Strict
}

// SetName sets the value of Name.
func (s *CreateChatCompletionRequestResponseFormatJSONSchema) SetName(val OptString) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateChatCompletionRequestResponseFormatJSONSchema) SetDescription(val OptString) {
	s.Description = val
}

// SetSchema sets the value of Schema.
func (s *CreateChatCompletionRequestResponseFormatJSONSchema) SetSchema(val OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema) {
	s.Schema = val
}

// SetStrict sets the value of Strict.
func (s *CreateChatCompletionRequestResponseFormatJSONSchema) SetStrict(val OptNilBool) {
	s.Strict = val
}

type CreateChatCompletionRequestResponseFormatJSONSchemaSchema map[string]jx.Raw

func (s *CreateChatCompletionRequestResponseFormatJSONSchemaSchema) init() CreateChatCompletionRequestResponseFormatJSONSchemaSchema {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type CreateChatCompletionRequestResponseFormatType string

const (
	CreateChatCompletionRequestResponseFormatTypeText       CreateChatCompletionRequestResponseFormatType = "text"
	CreateChatCompletionRequestResponseFormatTypeJSONObject CreateChatCompletionRequestResponseFormatType = "json_object"
	CreateChatCompletionRequestResponseFormatTypeJSONSchema CreateChatCompletionRequestResponseFormatType = "json_schema"
)

// AllValues returns all CreateChatCompletionRequestResponseFormatType values.
func (CreateChatCompletionRequestResponseFormatType) AllValues() []CreateChatCompletionRequestResponseFormatType {
	return []CreateChatCompletionRequestResponseFormatType{
		CreateChatCompletionRequestResponseFormatTypeText,
		CreateChatCompletionRequestResponseFormatTypeJSONObject,
		CreateChatCompletionRequestResponseFormatTypeJSONSchema,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateChatCompletionRequestResponseFormatType) MarshalText() ([]byte, error) {
	switch s {
	case CreateChatCompletionRequestResponseFormatTypeText:
		return []byte(s), nil
	case CreateChatCompletionRequestResponseFormatTypeJSONObject:
		return []byte(s), nil
	case CreateChatCompletionRequestResponseFormatTypeJSONSchema:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateChatCompletionRequestResponseFormatType) UnmarshalText(data []byte) error {
	switch CreateChatCompletionRequestResponseFormatType(data) {
	case CreateChatCompletionRequestResponseFormatTypeText:
		*s = CreateChatCompletionRequestResponseFormatTypeText
		return nil
	case CreateChatCompletionRequestResponseFormatTypeJSONObject:
		*s = CreateChatCompletionRequestResponseFormatTypeJSONObject
		return nil
	case CreateChatCompletionRequestResponseFormatTypeJSONSchema:
		*s = CreateChatCompletionRequestResponseFormatTypeJSONSchema
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// CreateChatCompletionRequestStop represents sum type.
type CreateChatCompletionRequestStop struct {
	Type        CreateChatCompletionRequestStopType // switch on this field
	String      string
	StringArray []string
}

// CreateChatCompletionRequestStopType is oneOf type of CreateChatCompletionRequestStop.
type CreateChatCompletionRequestStopType string

// Possible values for CreateChatCompletionRequestStopType.
const (
	StringCreateChatCompletionRequestStop      CreateChatCompletionRequestStopType = "string"
	StringArrayCreateChatCompletionRequestStop CreateChatCompletionRequestStopType = "[]string"
)

// IsString reports whether CreateChatCompletionRequestStop is string.
func (s CreateChatCompletionRequestStop) IsString() bool {
	return s.Type == StringCreateChatCompletionRequestStop
}

// IsStringArray reports whether CreateChatCompletionRequestStop is []string.
func (s CreateChatCompletionRequestStop) IsStringArray() bool {
	return s.Type == StringArrayCreateChatCompletionRequestStop
}

// SetString sets CreateChatCompletionRequestStop to string.
func (s *CreateChatCompletionRequestStop) SetString(v string) {
	s.Type = StringCreateChatCompletionRequestStop
	s.String = v
}

// GetString returns string and true boolean if CreateChatCompletionRequestStop is string.
func (s CreateChatCompletionRequestStop) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringCreateChatCompletionRequestStop returns new CreateChatCompletionRequestStop from string.
func NewStringCreateChatCompletionRequestStop(v string) CreateChatCompletionRequestStop {
	var s CreateChatCompletionRequestStop
	s.SetString(v)
	return s
}

// SetStringArray sets CreateChatCompletionRequestStop to []string.
func (s *CreateChatCompletionRequestStop) SetStringArray(v []string) {
	s.Type = StringArrayCreateChatCompletionRequestStop
	s.StringArray = v
}

// GetStringArray returns []string and true boolean if CreateChatCompletionRequestStop is []string.
func (s CreateChatCompletionRequestStop) GetStringArray() (v []string, ok bool) {
	if !s.IsStringArray() {
		return v, false
	}
	return s.StringArray, true
}

// NewStringArrayCreateChatCompletionRequestStop returns new CreateChatCompletionRequestStop from []string.
func NewStringArrayCreateChatCompletionRequestStop(v []string) CreateChatCompletionRequestStop {
	var s CreateChatCompletionRequestStop
	s.SetStringArray(v)
	return s
}

type CreateChatCompletionRequestStreamOptions struct {
	IncludeUsage OptBool `json:"include_usage"`
}

// GetIncludeUsage returns the value of IncludeUsage.
func (s *CreateChatCompletionRequestStreamOptions) GetIncludeUsage() OptBool {
	return s.IncludeUsage
}

// SetIncludeUsage sets the value of IncludeUsage.
func (s *CreateChatCompletionRequestStreamOptions) SetIncludeUsage(val OptBool) {
	s.IncludeUsage = val
}

// CreateChatCompletionRequestToolChoice represents sum type.
type CreateChatCompletionRequestToolChoice struct {
	Type                                   CreateChatCompletionRequestToolChoiceType // switch on this field
	CreateChatCompletionRequestToolChoice0 CreateChatCompletionRequestToolChoice0
	ChatCompletionNamedToolChoice          ChatCompletionNamedToolChoice
}

// CreateChatCompletionRequestToolChoiceType is oneOf type of CreateChatCompletionRequestToolChoice.
type CreateChatCompletionRequestToolChoiceType string

// Possible values for CreateChatCompletionRequestToolChoiceType.
const (
	CreateChatCompletionRequestToolChoice0CreateChatCompletionRequestToolChoice CreateChatCompletionRequestToolChoiceType = "CreateChatCompletionRequestToolChoice0"
	ChatCompletionNamedToolChoiceCreateChatCompletionRequestToolChoice          CreateChatCompletionRequestToolChoiceType = "ChatCompletionNamedToolChoice"
)

// IsCreateChatCompletionRequestToolChoice0 reports whether CreateChatCompletionRequestToolChoice is CreateChatCompletionRequestToolChoice0.
func (s CreateChatCompletionRequestToolChoice) IsCreateChatCompletionRequestToolChoice0() bool {
	return s.Type == CreateChatCompletionRequestToolChoice0CreateChatCompletionRequestToolChoice
}

// IsChatCompletionNamedToolChoice reports whether CreateChatCompletionRequestToolChoice is ChatCompletionNamedToolChoice.
func (s CreateChatCompletionRequestToolChoice) IsChatCompletionNamedToolChoice() bool {
	return s.Type == ChatCompletionNamedToolChoiceCreateChatCompletionRequestToolChoice
}

// SetCreateChatCompletionRequestToolChoice0 sets CreateChatCompletionRequestToolChoice to CreateChatCompletionRequestToolChoice0.
func (s *CreateChatCompletionRequestToolChoice) SetCreateChatCompletionRequestToolChoice0(v CreateChatCompletionRequestToolChoice0) {
	s.Type = CreateChatCompletionRequestToolChoice0CreateChatCompletionRequestToolChoice
	s.CreateChatCompletionRequestToolChoice0 = v
}

// GetCreateChatCompletionRequestToolChoice0 returns CreateChatCompletionRequestToolChoice0 and true boolean if CreateChatCompletionRequestToolChoice is CreateChatCompletionRequestToolChoice0.
func (s CreateChatCompletionRequestToolChoice) GetCreateChatCompletionRequestToolChoice0() (v CreateChatCompletionRequestToolChoice0, ok bool) {
	if !s.IsCreateChatCompletionRequestToolChoice0() {
		return v, false
	}
	return s.CreateChatCompletionRequestToolChoice0, true
}

// NewCreateChatCompletionRequestToolChoice0CreateChatCompletionRequestToolChoice returns new CreateChatCompletionRequestToolChoice from CreateChatCompletionRequestToolChoice0.
func NewCreateChatCompletionRequestToolChoice0CreateChatCompletionRequestToolChoice(v CreateChatCompletionRequestToolChoice0) CreateChatCompletionRequestToolChoice {
	var s CreateChatCompletionRequestToolChoice
	s.SetCreateChatCompletionRequestToolChoice0(v)
	return s
}

// SetChatCompletionNamedToolChoice sets CreateChatCompletionRequestToolChoice to ChatCompletionNamedToolChoice.
func (s *CreateChatCompletionRequestToolChoice) SetChatCompletionNamedToolChoice(v ChatCompletionNamedToolChoice) {
	s.Type = ChatCompletionNamedToolChoiceCreateChatCompletionRequestToolChoice
	s.ChatCompletionNamedToolChoice = v
}

// GetChatCompletionNamedToolChoice returns ChatCompletionNamedToolChoice and true boolean if CreateChatCompletionRequestToolChoice is ChatCompletionNamedToolChoice.
func (s CreateChatCompletionRequestToolChoice) GetChatCompletionNamedToolChoice() (v ChatCompletionNamedToolChoice, ok bool) {
	if !s.IsChatCompletionNamedToolChoice() {
		return v, false
	}
	return s.ChatCompletionNamedToolChoice, true
}

// NewChatCompletionNamedToolChoiceCreateChatCompletionRequestToolChoice returns new CreateChatCompletionRequestToolChoice from ChatCompletionNamedToolChoice.
func NewChatCompletionNamedToolChoiceCreateChatCompletionRequestToolChoice(v ChatCompletionNamedToolChoice) CreateChatCompletionRequestToolChoice {
	var s CreateChatCompletionRequestToolChoice
	s.SetChatCompletionNamedToolChoice(v)
	return s
}

type CreateChatCompletionRequestToolChoice0 string

const (
	CreateChatCompletionRequestToolChoice0None     CreateChatCompletionRequestToolChoice0 = "none"
	CreateChatCompletionRequestToolChoice0Auto     CreateChatCompletionRequestToolChoice0 = "auto"
	CreateChatCompletionRequestToolChoice0Required CreateChatCompletionRequestToolChoice0 = "required"
)

// AllValues returns all CreateChatCompletionRequestToolChoice0 values.
func (CreateChatCompletionRequestToolChoice0) AllValues() []CreateChatCompletionRequestToolChoice0 {
	return []CreateChatCompletionRequestToolChoice0{
		CreateChatCompletionRequestToolChoice0None,
		CreateChatCompletionRequestToolChoice0Auto,
		CreateChatCompletionRequestToolChoice0Required,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateChatCompletionRequestToolChoice0) MarshalText() ([]byte, error) {
	switch s {
	case CreateChatCompletionRequestToolChoice0None:
		return []byte(s), nil
	case CreateChatCompletionRequestToolChoice0Auto:
		return []byte(s), nil
	case CreateChatCompletionRequestToolChoice0Required:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateChatCompletionRequestToolChoice0) UnmarshalText(data []byte) error {
	switch CreateChatCompletionRequestToolChoice0(data) {
	case CreateChatCompletionRequestToolChoice0None:
		*s = CreateChatCompletionRequestToolChoice0None
		return nil
	case CreateChatCompletionRequestToolChoice0Auto:
		*s = CreateChatCompletionRequestToolChoice0Auto
		return nil
	case CreateChatCompletionRequestToolChoice0Required:
		*s = CreateChatCompletionRequestToolChoice0Required
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CreateChatCompletionResponse
type CreateChatCompletionResponse struct {
	ID                string                             `json:"id"`
	Object            CreateChatCompletionResponseObject `json:"object"`
	Created           int                                `json:"created"`
	Model             string                             `json:"model"`
	Choices           []ChatCompletionChoice             `json:"choices"`
	Usage             OptCompletionUsage                 `json:"usage"`
	SystemFingerprint OptString                          `json:"system_fingerprint"`
	ServiceTier       OptNilString                       `json:"service_tier"`
}

// GetID returns the value of ID.
func (s *CreateChatCompletionResponse) GetID() string {
	return s.ID
}

// GetObject returns the value of Object.
func (s *CreateChatCompletionResponse) GetObject() CreateChatCompletionResponseObject {
	return s.Object
}

// GetCreated returns the value of Created.
func (s *CreateChatCompletionResponse) GetCreated() int {
	return s.Created
}

// GetModel returns the value of Model.
func (s *CreateChatCompletionResponse) GetModel() string {
	return s.Model
}

// GetChoices returns the value of Choices.
func (s *CreateChatCompletionResponse) GetChoices() []ChatCompletionChoice {
	return s.Choices
}

// GetUsage returns the value of Usage.
func (s *CreateChatCompletionResponse) GetUsage() OptCompletionUsage {
	return s.Usage
}

// GetSystemFingerprint returns the value of SystemFingerprint.
func (s *CreateChatCompletionResponse) GetSystemFingerprint() OptString {
	return s.SystemFingerprint
}

// GetServiceTier returns the value of ServiceTier.
func (s *CreateChatCompletionResponse) GetServiceTier() OptNilString {
	return s.ServiceTier
}

// SetID sets the value of ID.
func (s *CreateChatCompletionResponse) SetID(val string) {
	s.ID = val
}

// SetObject sets the value of Object.
func (s *CreateChatCompletionResponse) SetObject(val CreateChatCompletionResponseObject) {
	s.Object = val
}

// SetCreated sets the value of Created.
func (s *CreateChatCompletionResponse) SetCreated(val int) {
	s.Created = val
}

// SetModel sets the value of Model.
func (s *CreateChatCompletionResponse) SetModel(val string) {
	s.Model = val
}

// SetChoices sets the value of Choices.
func (s *CreateChatCompletionResponse) SetChoices(val []ChatCompletionChoice) {
	s.Choices = val
}

// SetUsage sets the value of Usage.
func (s *CreateChatCompletionResponse) SetUsage(val OptCompletionUsage) {
	s.Usage = val
}

// SetSystemFingerprint sets the value of SystemFingerprint.
func (s *CreateChatCompletionResponse) SetSystemFingerprint(val OptString) {
	s.SystemFingerprint = val
}

// SetServiceTier sets the value of ServiceTier.
func (s *CreateChatCompletionResponse) SetServiceTier(val OptNilString) {
	s.ServiceTier = val
}

type CreateChatCompletionResponseObject string

const (
	CreateChatCompletionResponseObjectChatCompletion CreateChatCompletionResponseObject = "chat.completion"
)

// AllValues returns all CreateChatCompletionResponseObject values.
func (CreateChatCompletionResponseObject) AllValues() []CreateChatCompletionResponseObject {
	return []CreateChatCompletionResponseObject{
		CreateChatCompletionResponseObjectChatCompletion,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateChatCompletionResponseObject) MarshalText() ([]byte, error) {
	switch s {
	case CreateChatCompletionResponseObjectChatCompletion:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateChatCompletionResponseObject) UnmarshalText(data []byte) error {
	switch CreateChatCompletionResponseObject(data) {
	case CreateChatCompletionResponseObjectChatCompletion:
		*s = CreateChatCompletionResponseObjectChatCompletion
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/FunctionObject
type FunctionObject struct {
	Name        string                      `json:"name"`
	Description OptString                   `json:"description"`
	Parameters  OptFunctionObjectParameters `json:"parameters"`
	Strict      OptNilBool                  `json:"strict"`
}

// GetName returns the value of Name.
func (s *FunctionObject) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *FunctionObject) GetDescription() OptString {
	return s.Description
}

// GetParameters returns the value of Parameters.
func (s *FunctionObject) GetParameters() OptFunctionObjectParameters {
	return s.Parameters
}

// GetStrict returns the value of Strict.
func (s *FunctionObject) GetStrict() OptNilBool {
	return s.Strict
}

// SetName sets the value of Name.
func (s *FunctionObject) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *FunctionObject) SetDescription(val OptString) {
	s.Description = val
}

// SetParameters sets the value of Parameters.
func (s *FunctionObject) SetParameters(val OptFunctionObjectParameters) {
	s.Parameters = val
}

// SetStrict sets the value of Strict.
func (s *FunctionObject) SetStrict(val OptNilBool) {
	s.Strict = val
}

type FunctionObjectParameters map[string]jx.Raw

func (s *FunctionObjectParameters) init() FunctionObjectParameters {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/ListModelsResponse
type ListModelsResponse struct {
	Object ListModelsResponseObject `json:"object"`
	Data   []Model                  `json:"data"`
}

// GetObject returns the value of Object.
func (s *ListModelsResponse) GetObject() ListModelsResponseObject {
	return s.Object
}

// GetData returns the value of Data.
func (s *ListModelsResponse) GetData() []Model {
	return s.Data
}

// SetObject sets the value of Object.
func (s *ListModelsResponse) SetObject(val ListModelsResponseObject) {
	s.Object = val
}

// SetData sets the value of Data.
func (s *ListModelsResponse) SetData(val []Model) {
	s.Data = val
}

type ListModelsResponseObject string

const (
	ListModelsResponseObjectList ListModelsResponseObject = "list"
)

// AllValues returns all ListModelsResponseObject values.
func (ListModelsResponseObject) AllValues() []ListModelsResponseObject {
	return []ListModelsResponseObject{
		ListModelsResponseObjectList,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListModelsResponseObject) MarshalText() ([]byte, error) {
	switch s {
	case ListModelsResponseObjectList:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListModelsResponseObject) UnmarshalText(data []byte) error {
	switch ListModelsResponseObject(data) {
	case ListModelsResponseObjectList:
		*s = ListModelsResponseObjectList
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Model
type Model struct {
	ID      string      `json:"id"`
	Object  ModelObject `json:"object"`
	Created int         `json:"created"`
	OwnedBy string      `json:"owned_by"`
}

// GetID returns the value of ID.
func (s *Model) GetID() string {
	return s.ID
}

// GetObject returns the value of Object.
func (s *Model) GetObject() ModelObject {
	return s.Object
}

// GetCreated returns the value of Created.
func (s *Model) GetCreated() int {
	return s.Created
}

// GetOwnedBy returns the value of OwnedBy.
func (s *Model) GetOwnedBy() string {
	return s.OwnedBy
}

// SetID sets the value of ID.
func (s *Model) SetID(val string) {
	s.ID = val
}

// SetObject sets the value of Object.
func (s *Model) SetObject(val ModelObject) {
	s.Object = val
}

// SetCreated sets the value of Created.
func (s *Model) SetCreated(val int) {
	s.Created = val
}

// SetOwnedBy sets the value of OwnedBy.
func (s *Model) SetOwnedBy(val string) {
	s.OwnedBy = val
}

type ModelObject string

const (
	ModelObjectModel ModelObject = "model"
)

// AllValues returns all ModelObject values.
func (ModelObject) AllValues() []ModelObject {
	return []ModelObject{
		ModelObjectModel,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ModelObject) MarshalText() ([]byte, error) {
	switch s {
	case ModelObjectModel:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ModelObject) UnmarshalText(data []byte) error {
	switch ModelObject(data) {
	case ModelObjectModel:
		*s = ModelObjectModel
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewNilChatCompletionChoiceFinishReason returns new NilChatCompletionChoiceFinishReason with value set to v.
func NewNilChatCompletionChoiceFinishReason(v ChatCompletionChoiceFinishReason) NilChatCompletionChoiceFinishReason {
	return NilChatCompletionChoiceFinishReason{
		Value: v,
	}
}

// NilChatCompletionChoiceFinishReason is nullable ChatCompletionChoiceFinishReason.
type NilChatCompletionChoiceFinishReason struct {
	Value ChatCompletionChoiceFinishReason
	Null  bool
}

// SetTo sets value to v.
func (o *NilChatCompletionChoiceFinishReason) SetTo(v ChatCompletionChoiceFinishReason) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilChatCompletionChoiceFinishReason) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilChatCompletionChoiceFinishReason) SetToNull() {
	o.Null = true
	var v ChatCompletionChoiceFinishReason
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilChatCompletionChoiceFinishReason) Get() (v ChatCompletionChoiceFinishReason, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilChatCompletionChoiceFinishReason) Or(d ChatCompletionChoiceFinishReason) ChatCompletionChoiceFinishReason {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptChatCompletionContentPartImageURL returns new OptChatCompletionContentPartImageURL with value set to v.
func NewOptChatCompletionContentPartImageURL(v ChatCompletionContentPartImageURL) OptChatCompletionContentPartImageURL {
	return OptChatCompletionContentPartImageURL{
		Value: v,
		Set:   true,
	}
}

// OptChatCompletionContentPartImageURL is optional ChatCompletionContentPartImageURL.
type OptChatCompletionContentPartImageURL struct {
	Value ChatCompletionContentPartImageURL
	Set   bool
}

// IsSet returns true if OptChatCompletionContentPartImageURL was set.
func (o OptChatCompletionContentPartImageURL) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptChatCompletionContentPartImageURL) Reset() {
	var v ChatCompletionContentPartImageURL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptChatCompletionContentPartImageURL) SetTo(v ChatCompletionContentPartImageURL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptChatCompletionContentPartImageURL) Get() (v ChatCompletionContentPartImageURL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptChatCompletionContentPartImageURL) Or(d ChatCompletionContentPartImageURL) ChatCompletionContentPartImageURL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptChatCompletionContentPartImageURLDetail returns new OptChatCompletionContentPartImageURLDetail with value set to v.
func NewOptChatCompletionContentPartImageURLDetail(v ChatCompletionContentPartImageURLDetail) OptChatCompletionContentPartImageURLDetail {
	return OptChatCompletionContentPartImageURLDetail{
		Value: v,
		Set:   true,
	}
}

// OptChatCompletionContentPartImageURLDetail is optional ChatCompletionContentPartImageURLDetail.
type OptChatCompletionContentPartImageURLDetail struct {
	Value ChatCompletionContentPartImageURLDetail
	Set   bool
}

// IsSet returns true if OptChatCompletionContentPartImageURLDetail was set.
func (o OptChatCompletionContentPartImageURLDetail) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptChatCompletionContentPartImageURLDetail) Reset() {
	var v ChatCompletionContentPartImageURLDetail
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptChatCompletionContentPartImageURLDetail) SetTo(v ChatCompletionContentPartImageURLDetail) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptChatCompletionContentPartImageURLDetail) Get() (v ChatCompletionContentPartImageURLDetail, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptChatCompletionContentPartImageURLDetail) Or(d ChatCompletionContentPartImageURLDetail) ChatCompletionContentPartImageURLDetail {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCompletionUsage returns new OptCompletionUsage with value set to v.
func NewOptCompletionUsage(v CompletionUsage) OptCompletionUsage {
	return OptCompletionUsage{
		Value: v,
		Set:   true,
	}
}

// OptCompletionUsage is optional CompletionUsage.
type OptCompletionUsage struct {
	Value CompletionUsage
	Set   bool
}

// IsSet returns true if OptCompletionUsage was set.
func (o OptCompletionUsage) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCompletionUsage) Reset() {
	var v CompletionUsage
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCompletionUsage) SetTo(v CompletionUsage) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCompletionUsage) Get() (v CompletionUsage, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCompletionUsage) Or(d CompletionUsage) CompletionUsage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCompletionUsageCompletionTokensDetails returns new OptCompletionUsageCompletionTokensDetails with value set to v.
func NewOptCompletionUsageCompletionTokensDetails(v CompletionUsageCompletionTokensDetails) OptCompletionUsageCompletionTokensDetails {
	return OptCompletionUsageCompletionTokensDetails{
		Value: v,
		Set:   true,
	}
}

// OptCompletionUsageCompletionTokensDetails is optional CompletionUsageCompletionTokensDetails.
type OptCompletionUsageCompletionTokensDetails struct {
	Value CompletionUsageCompletionTokensDetails
	Set   bool
}

// IsSet returns true if OptCompletionUsageCompletionTokensDetails was set.
func (o OptCompletionUsageCompletionTokensDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCompletionUsageCompletionTokensDetails) Reset() {
	var v CompletionUsageCompletionTokensDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCompletionUsageCompletionTokensDetails) SetTo(v CompletionUsageCompletionTokensDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCompletionUsageCompletionTokensDetails) Get() (v CompletionUsageCompletionTokensDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCompletionUsageCompletionTokensDetails) Or(d CompletionUsageCompletionTokensDetails) CompletionUsageCompletionTokensDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCompletionUsagePromptTokensDetails returns new OptCompletionUsagePromptTokensDetails with value set to v.
func NewOptCompletionUsagePromptTokensDetails(v CompletionUsagePromptTokensDetails) OptCompletionUsagePromptTokensDetails {
	return OptCompletionUsagePromptTokensDetails{
		Value: v,
		Set:   true,
	}
}

// OptCompletionUsagePromptTokensDetails is optional CompletionUsagePromptTokensDetails.
type OptCompletionUsagePromptTokensDetails struct {
	Value CompletionUsagePromptTokensDetails
	Set   bool
}

// IsSet returns true if OptCompletionUsagePromptTokensDetails was set.
func (o OptCompletionUsagePromptTokensDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCompletionUsagePromptTokensDetails) Reset() {
	var v CompletionUsagePromptTokensDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCompletionUsagePromptTokensDetails) SetTo(v CompletionUsagePromptTokensDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCompletionUsagePromptTokensDetails) Get() (v CompletionUsagePromptTokensDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCompletionUsagePromptTokensDetails) Or(d CompletionUsagePromptTokensDetails) CompletionUsagePromptTokensDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateChatCompletionRequestResponseFormat returns new OptCreateChatCompletionRequestResponseFormat with value set to v.
func NewOptCreateChatCompletionRequestResponseFormat(v CreateChatCompletionRequestResponseFormat) OptCreateChatCompletionRequestResponseFormat {
	return OptCreateChatCompletionRequestResponseFormat{
		Value: v,
		Set:   true,
	}
}

// OptCreateChatCompletionRequestResponseFormat is optional CreateChatCompletionRequestResponseFormat.
type OptCreateChatCompletionRequestResponseFormat struct {
	Value CreateChatCompletionRequestResponseFormat
	Set   bool
}

// IsSet returns true if OptCreateChatCompletionRequestResponseFormat was set.
func (o OptCreateChatCompletionRequestResponseFormat) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateChatCompletionRequestResponseFormat) Reset() {
	var v CreateChatCompletionRequestResponseFormat
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateChatCompletionRequestResponseFormat) SetTo(v CreateChatCompletionRequestResponseFormat) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateChatCompletionRequestResponseFormat) Get() (v CreateChatCompletionRequestResponseFormat, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateChatCompletionRequestResponseFormat) Or(d CreateChatCompletionRequestResponseFormat) CreateChatCompletionRequestResponseFormat {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateChatCompletionRequestResponseFormatJSONSchema returns new OptCreateChatCompletionRequestResponseFormatJSONSchema with value set to v.
func NewOptCreateChatCompletionRequestResponseFormatJSONSchema(v CreateChatCompletionRequestResponseFormatJSONSchema) OptCreateChatCompletionRequestResponseFormatJSONSchema {
	return OptCreateChatCompletionRequestResponseFormatJSONSchema{
		Value: v,
		Set:   true,
	}
}

// OptCreateChatCompletionRequestResponseFormatJSONSchema is optional CreateChatCompletionRequestResponseFormatJSONSchema.
type OptCreateChatCompletionRequestResponseFormatJSONSchema struct {
	Value CreateChatCompletionRequestResponseFormatJSONSchema
	Set   bool
}

// IsSet returns true if OptCreateChatCompletionRequestResponseFormatJSONSchema was set.
func (o OptCreateChatCompletionRequestResponseFormatJSONSchema) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateChatCompletionRequestResponseFormatJSONSchema) Reset() {
	var v CreateChatCompletionRequestResponseFormatJSONSchema
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateChatCompletionRequestResponseFormatJSONSchema) SetTo(v CreateChatCompletionRequestResponseFormatJSONSchema) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateChatCompletionRequestResponseFormatJSONSchema) Get() (v CreateChatCompletionRequestResponseFormatJSONSchema, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateChatCompletionRequestResponseFormatJSONSchema) Or(d CreateChatCompletionRequestResponseFormatJSONSchema) CreateChatCompletionRequestResponseFormatJSONSchema {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateChatCompletionRequestResponseFormatJSONSchemaSchema returns new OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema with value set to v.
func NewOptCreateChatCompletionRequestResponseFormatJSONSchemaSchema(v CreateChatCompletionRequestResponseFormatJSONSchemaSchema) OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema {
	return OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema{
		Value: v,
		Set:   true,
	}
}

// OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema is optional CreateChatCompletionRequestResponseFormatJSONSchemaSchema.
type OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema struct {
	Value CreateChatCompletionRequestResponseFormatJSONSchemaSchema
	Set   bool
}

// IsSet returns true if OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema was set.
func (o OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema) Reset() {
	var v CreateChatCompletionRequestResponseFormatJSONSchemaSchema
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema) SetTo(v CreateChatCompletionRequestResponseFormatJSONSchemaSchema) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema) Get() (v CreateChatCompletionRequestResponseFormatJSONSchemaSchema, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateChatCompletionRequestResponseFormatJSONSchemaSchema) Or(d CreateChatCompletionRequestResponseFormatJSONSchemaSchema) CreateChatCompletionRequestResponseFormatJSONSchemaSchema {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateChatCompletionRequestResponseFormatType returns new OptCreateChatCompletionRequestResponseFormatType with value set to v.
func NewOptCreateChatCompletionRequestResponseFormatType(v CreateChatCompletionRequestResponseFormatType) OptCreateChatCompletionRequestResponseFormatType {
	return OptCreateChatCompletionRequestResponseFormatType{
		Value: v,
		Set:   true,
	}
}

// OptCreateChatCompletionRequestResponseFormatType is optional CreateChatCompletionRequestResponseFormatType.
type OptCreateChatCompletionRequestResponseFormatType struct {
	Value CreateChatCompletionRequestResponseFormatType
	Set   bool
}

// IsSet returns true if OptCreateChatCompletionRequestResponseFormatType was set.
func (o OptCreateChatCompletionRequestResponseFormatType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateChatCompletionRequestResponseFormatType) Reset() {
	var v CreateChatCompletionRequestResponseFormatType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateChatCompletionRequestResponseFormatType) SetTo(v CreateChatCompletionRequestResponseFormatType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateChatCompletionRequestResponseFormatType) Get() (v CreateChatCompletionRequestResponseFormatType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateChatCompletionRequestResponseFormatType) Or(d CreateChatCompletionRequestResponseFormatType) CreateChatCompletionRequestResponseFormatType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateChatCompletionRequestToolChoice returns new OptCreateChatCompletionRequestToolChoice with value set to v.
func NewOptCreateChatCompletionRequestToolChoice(v CreateChatCompletionRequestToolChoice) OptCreateChatCompletionRequestToolChoice {
	return OptCreateChatCompletionRequestToolChoice{
		Value: v,
		Set:   true,
	}
}

// OptCreateChatCompletionRequestToolChoice is optional CreateChatCompletionRequestToolChoice.
type OptCreateChatCompletionRequestToolChoice struct {
	Value CreateChatCompletionRequestToolChoice
	Set   bool
}

// IsSet returns true if OptCreateChatCompletionRequestToolChoice was set.
func (o OptCreateChatCompletionRequestToolChoice) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateChatCompletionRequestToolChoice) Reset() {
	var v CreateChatCompletionRequestToolChoice
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateChatCompletionRequestToolChoice) SetTo(v CreateChatCompletionRequestToolChoice) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateChatCompletionRequestToolChoice) Get() (v CreateChatCompletionRequestToolChoice, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateChatCompletionRequestToolChoice) Or(d CreateChatCompletionRequestToolChoice) CreateChatCompletionRequestToolChoice {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFunctionObjectParameters returns new OptFunctionObjectParameters with value set to v.
func NewOptFunctionObjectParameters(v FunctionObjectParameters) OptFunctionObjectParameters {
	return OptFunctionObjectParameters{
		Value: v,
		Set:   true,
	}
}

// OptFunctionObjectParameters is optional FunctionObjectParameters.
type OptFunctionObjectParameters struct {
	Value FunctionObjectParameters
	Set   bool
}

// IsSet returns true if OptFunctionObjectParameters was set.
func (o OptFunctionObjectParameters) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFunctionObjectParameters) Reset() {
	var v FunctionObjectParameters
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFunctionObjectParameters) SetTo(v FunctionObjectParameters) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFunctionObjectParameters) Get() (v FunctionObjectParameters, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFunctionObjectParameters) Or(d FunctionObjectParameters) FunctionObjectParameters {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilBool returns new OptNilBool with value set to v.
func NewOptNilBool(v bool) OptNilBool {
	return OptNilBool{
		Value: v,
		Set:   true,
	}
}

// OptNilBool is optional nullable bool.
type OptNilBool struct {
	Value bool
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilBool was set.
func (o OptNilBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilBool) SetTo(v bool) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilBool) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilBool) SetToNull() {
	o.Set = true
	o.Null = true
	var v bool
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilBool) Get() (v bool, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilChatCompletionChoiceLogprobs returns new OptNilChatCompletionChoiceLogprobs with value set to v.
func NewOptNilChatCompletionChoiceLogprobs(v ChatCompletionChoiceLogprobs) OptNilChatCompletionChoiceLogprobs {
	return OptNilChatCompletionChoiceLogprobs{
		Value: v,
		Set:   true,
	}
}

// OptNilChatCompletionChoiceLogprobs is optional nullable ChatCompletionChoiceLogprobs.
type OptNilChatCompletionChoiceLogprobs struct {
	Value ChatCompletionChoiceLogprobs
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilChatCompletionChoiceLogprobs was set.
func (o OptNilChatCompletionChoiceLogprobs) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilChatCompletionChoiceLogprobs) Reset() {
	var v ChatCompletionChoiceLogprobs
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilChatCompletionChoiceLogprobs) SetTo(v ChatCompletionChoiceLogprobs) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilChatCompletionChoiceLogprobs) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilChatCompletionChoiceLogprobs) SetToNull() {
	o.Set = true
	o.Null = true
	var v ChatCompletionChoiceLogprobs
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilChatCompletionChoiceLogprobs) Get() (v ChatCompletionChoiceLogprobs, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilChatCompletionChoiceLogprobs) Or(d ChatCompletionChoiceLogprobs) ChatCompletionChoiceLogprobs {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilChatCompletionRequestMessageContent returns new OptNilChatCompletionRequestMessageContent with value set to v.
func NewOptNilChatCompletionRequestMessageContent(v ChatCompletionRequestMessageContent) OptNilChatCompletionRequestMessageContent {
	return OptNilChatCompletionRequestMessageContent{
		Value: v,
		Set:   true,
	}
}

// OptNilChatCompletionRequestMessageContent is optional nullable ChatCompletionRequestMessageContent.
type OptNilChatCompletionRequestMessageContent struct {
	Value ChatCompletionRequestMessageContent
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilChatCompletionRequestMessageContent was set.
func (o OptNilChatCompletionRequestMessageContent) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilChatCompletionRequestMessageContent) Reset() {
	var v ChatCompletionRequestMessageContent
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilChatCompletionRequestMessageContent) SetTo(v ChatCompletionRequestMessageContent) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilChatCompletionRequestMessageContent) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilChatCompletionRequestMessageContent) SetToNull() {
	o.Set = true
	o.Null = true
	var v ChatCompletionRequestMessageContent
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilChatCompletionRequestMessageContent) Get() (v ChatCompletionRequestMessageContent, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilChatCompletionRequestMessageContent) Or(d ChatCompletionRequestMessageContent) ChatCompletionRequestMessageContent {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilChatCompletionTokenLogprobArray returns new OptNilChatCompletionTokenLogprobArray with value set to v.
func NewOptNilChatCompletionTokenLogprobArray(v []ChatCompletionTokenLogprob) OptNilChatCompletionTokenLogprobArray {
	return OptNilChatCompletionTokenLogprobArray{
		Value: v,
		Set:   true,
	}
}

// OptNilChatCompletionTokenLogprobArray is optional nullable []ChatCompletionTokenLogprob.
type OptNilChatCompletionTokenLogprobArray struct {
	Value []ChatCompletionTokenLogprob
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilChatCompletionTokenLogprobArray was set.
func (o OptNilChatCompletionTokenLogprobArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilChatCompletionTokenLogprobArray) Reset() {
	var v []ChatCompletionTokenLogprob
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilChatCompletionTokenLogprobArray) SetTo(v []ChatCompletionTokenLogprob) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilChatCompletionTokenLogprobArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilChatCompletionTokenLogprobArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ChatCompletionTokenLogprob
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilChatCompletionTokenLogprobArray) Get() (v []ChatCompletionTokenLogprob, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilChatCompletionTokenLogprobArray) Or(d []ChatCompletionTokenLogprob) []ChatCompletionTokenLogprob {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilCreateChatCompletionRequestLogitBias returns new OptNilCreateChatCompletionRequestLogitBias with value set to v.
func NewOptNilCreateChatCompletionRequestLogitBias(v CreateChatCompletionRequestLogitBias) OptNilCreateChatCompletionRequestLogitBias {
	return OptNilCreateChatCompletionRequestLogitBias{
		Value: v,
		Set:   true,
	}
}

// OptNilCreateChatCompletionRequestLogitBias is optional nullable CreateChatCompletionRequestLogitBias.
type OptNilCreateChatCompletionRequestLogitBias struct {
	Value CreateChatCompletionRequestLogitBias
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilCreateChatCompletionRequestLogitBias was set.
func (o OptNilCreateChatCompletionRequestLogitBias) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilCreateChatCompletionRequestLogitBias) Reset() {
	var v CreateChatCompletionRequestLogitBias
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilCreateChatCompletionRequestLogitBias) SetTo(v CreateChatCompletionRequestLogitBias) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilCreateChatCompletionRequestLogitBias) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilCreateChatCompletionRequestLogitBias) SetToNull() {
	o.Set = true
	o.Null = true
	var v CreateChatCompletionRequestLogitBias
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilCreateChatCompletionRequestLogitBias) Get() (v CreateChatCompletionRequestLogitBias, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilCreateChatCompletionRequestLogitBias) Or(d CreateChatCompletionRequestLogitBias) CreateChatCompletionRequestLogitBias {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilCreateChatCompletionRequestStop returns new OptNilCreateChatCompletionRequestStop with value set to v.
func NewOptNilCreateChatCompletionRequestStop(v CreateChatCompletionRequestStop) OptNilCreateChatCompletionRequestStop {
	return OptNilCreateChatCompletionRequestStop{
		Value: v,
		Set:   true,
	}
}

// OptNilCreateChatCompletionRequestStop is optional nullable CreateChatCompletionRequestStop.
type OptNilCreateChatCompletionRequestStop struct {
	Value CreateChatCompletionRequestStop
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilCreateChatCompletionRequestStop was set.
func (o OptNilCreateChatCompletionRequestStop) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilCreateChatCompletionRequestStop) Reset() {
	var v CreateChatCompletionRequestStop
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilCreateChatCompletionRequestStop) SetTo(v CreateChatCompletionRequestStop) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilCreateChatCompletionRequestStop) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilCreateChatCompletionRequestStop) SetToNull() {
	o.Set = true
	o.Null = true
	var v CreateChatCompletionRequestStop
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilCreateChatCompletionRequestStop) Get() (v CreateChatCompletionRequestStop, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilCreateChatCompletionRequestStop) Or(d CreateChatCompletionRequestStop) CreateChatCompletionRequestStop {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilCreateChatCompletionRequestStreamOptions returns new OptNilCreateChatCompletionRequestStreamOptions with value set to v.
func NewOptNilCreateChatCompletionRequestStreamOptions(v CreateChatCompletionRequestStreamOptions) OptNilCreateChatCompletionRequestStreamOptions {
	return OptNilCreateChatCompletionRequestStreamOptions{
		Value: v,
		Set:   true,
	}
}

// OptNilCreateChatCompletionRequestStreamOptions is optional nullable CreateChatCompletionRequestStreamOptions.
type OptNilCreateChatCompletionRequestStreamOptions struct {
	Value CreateChatCompletionRequestStreamOptions
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilCreateChatCompletionRequestStreamOptions was set.
func (o OptNilCreateChatCompletionRequestStreamOptions) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilCreateChatCompletionRequestStreamOptions) Reset() {
	var v CreateChatCompletionRequestStreamOptions
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilCreateChatCompletionRequestStreamOptions) SetTo(v CreateChatCompletionRequestStreamOptions) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilCreateChatCompletionRequestStreamOptions) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilCreateChatCompletionRequestStreamOptions) SetToNull() {
	o.Set = true
	o.Null = true
	var v CreateChatCompletionRequestStreamOptions
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilCreateChatCompletionRequestStreamOptions) Get() (v CreateChatCompletionRequestStreamOptions, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilCreateChatCompletionRequestStreamOptions) Or(d CreateChatCompletionRequestStreamOptions) CreateChatCompletionRequestStreamOptions {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilFloat64 returns new OptNilFloat64 with value set to v.
func NewOptNilFloat64(v float64) OptNilFloat64 {
	return OptNilFloat64{
		Value: v,
		Set:   true,
	}
}

// OptNilFloat64 is optional nullable float64.
type OptNilFloat64 struct {
	Value float64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilFloat64 was set.
func (o OptNilFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilFloat64) SetTo(v float64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilFloat64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilFloat64) SetToNull() {
	o.Set = true
	o.Null = true
	var v float64
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilFloat64) Get() (v float64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt returns new OptNilInt with value set to v.
func NewOptNilInt(v int) OptNilInt {
	return OptNilInt{
		Value: v,
		Set:   true,
	}
}

// OptNilInt is optional nullable int.
type OptNilInt struct {
	Value int
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt was set.
func (o OptNilInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt) SetTo(v int) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt) SetToNull() {
	o.Set = true
	o.Null = true
	var v int
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
